# convert_layout.py — Extract text + preserve layout into Word
import sys, cv2, pytesseract
from docx import Document
from PIL import Image

image_path = sys.argv[1]
output_path = sys.argv[2]

# Load image
img = cv2.imread(image_path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# OCR config
custom_config = r'--oem 3 --psm 6'

# Detect words + positions
data = pytesseract.image_to_data(gray, config=custom_config, output_type=pytesseract.Output.DICT)
doc = Document()

for i in range(len(data["text"])):
    if int(data["conf"][i]) > 50:
        text = data["text"][i]
        if text.strip():
            doc.add_paragraph(text)

doc.add_paragraph("\n--- Generated by Pecipic.ai ---")
doc.save(output_path)
